default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Kartik@1212
  host: localhost

development:
  <<: *default
  database: employee_reimbursement_development

test:
  <<: *default
  database: employee_reimbursement_test

production:
  <<: *default
  database: employee_reimbursement_production
  username: your_production_username
  password: <%= ENV['EMPLOYEE_REIMBURSEMENT_DATABASE_PASSWORD'] %>
